<?php

return [
    'default_detection_provider' => env('FACE_SEARCH_DETECTION_PROVIDER', 'noop'),
    'default_embedding_provider' => env('FACE_SEARCH_EMBEDDING_PROVIDER', 'noop'),
    'default_vector_store' => env('FACE_SEARCH_VECTOR_STORE', 'pgvector'),
    'default_search_strategy' => env('FACE_SEARCH_SEARCH_STRATEGY', 'exact'),
    'default_embedding_model' => env('FACE_SEARCH_EMBEDDING_MODEL', 'face-embedding-foundation-v1'),
    'embedding_dimension' => (int) env('FACE_SEARCH_EMBEDDING_DIMENSION', 512),
    'crop_disk' => env('FACE_SEARCH_CROP_DISK', 'ai-private'),
    'min_face_size_px' => (int) env('FACE_SEARCH_MIN_FACE_SIZE_PX', 24),
    'min_quality_score' => (float) env('FACE_SEARCH_MIN_QUALITY_SCORE', 0.60),
    'search_threshold' => (float) env('FACE_SEARCH_SEARCH_THRESHOLD', 0.50),
    'top_k' => (int) env('FACE_SEARCH_TOP_K', 50),

    'ann' => [
        'hnsw_ef_search' => (int) env('FACE_SEARCH_HNSW_EF_SEARCH', 100),
        'hnsw_iterative_scan' => env('FACE_SEARCH_HNSW_ITERATIVE_SCAN', 'strict_order'),
    ],

    'quality' => [
        'search_priority_face_size_multiplier' => 1.35,
        'search_priority_quality_delta' => 0.10,
    ],

    'providers' => [
        'noop' => [
            'provider_version' => 'foundation-v1',
            'model' => 'noop-face-v1',
            'model_snapshot' => 'noop-face-v1',
        ],
        'compreface' => [
            'base_url' => env('FACE_SEARCH_COMPRE_FACE_BASE_URL', 'http://localhost:8000'),
            'api_key' => env('FACE_SEARCH_COMPRE_FACE_API_KEY', ''),
            'detection_api_key' => env('FACE_SEARCH_COMPRE_FACE_DETECTION_API_KEY', env('FACE_SEARCH_COMPRE_FACE_API_KEY', '')),
            'verification_api_key' => env('FACE_SEARCH_COMPRE_FACE_VERIFICATION_API_KEY', env('FACE_SEARCH_COMPRE_FACE_API_KEY', '')),
            'face_plugins' => env('FACE_SEARCH_COMPRE_FACE_FACE_PLUGINS', 'calculator,landmarks'),
            'det_prob_threshold' => env('FACE_SEARCH_COMPRE_FACE_DET_PROB_THRESHOLD'),
            'status' => (bool) env('FACE_SEARCH_COMPRE_FACE_STATUS', true),
            'timeout' => (int) env('FACE_SEARCH_COMPRE_FACE_TIMEOUT', 15),
            'detection_timeout' => (int) env('FACE_SEARCH_COMPRE_FACE_DETECTION_TIMEOUT', env('FACE_SEARCH_COMPRE_FACE_TIMEOUT', 25)),
            'verification_timeout' => (int) env('FACE_SEARCH_COMPRE_FACE_VERIFICATION_TIMEOUT', env('FACE_SEARCH_COMPRE_FACE_TIMEOUT', 15)),
            'connect_timeout' => (int) env('FACE_SEARCH_COMPRE_FACE_CONNECT_TIMEOUT', 5),
            'detection_connect_timeout' => (int) env('FACE_SEARCH_COMPRE_FACE_DETECTION_CONNECT_TIMEOUT', env('FACE_SEARCH_COMPRE_FACE_CONNECT_TIMEOUT', 5)),
            'verification_connect_timeout' => (int) env('FACE_SEARCH_COMPRE_FACE_VERIFICATION_CONNECT_TIMEOUT', env('FACE_SEARCH_COMPRE_FACE_CONNECT_TIMEOUT', 5)),
            'detection_retry_times' => (int) env('FACE_SEARCH_COMPRE_FACE_DETECTION_RETRY_TIMES', 3),
            'detection_retry_sleep_ms' => (int) env('FACE_SEARCH_COMPRE_FACE_DETECTION_RETRY_SLEEP_MS', 250),
            'verification_retry_times' => (int) env('FACE_SEARCH_COMPRE_FACE_VERIFICATION_RETRY_TIMES', 1),
            'verification_retry_sleep_ms' => (int) env('FACE_SEARCH_COMPRE_FACE_VERIFICATION_RETRY_SLEEP_MS', 100),
            'provider_version' => env('FACE_SEARCH_COMPRE_FACE_PROVIDER_VERSION', 'compreface-rest-v1'),
            'model' => env('FACE_SEARCH_COMPRE_FACE_MODEL', env('FACE_SEARCH_EMBEDDING_MODEL', 'compreface-face-v1')),
            'model_snapshot' => env('FACE_SEARCH_COMPRE_FACE_MODEL_SNAPSHOT', ''),
            'use_base64' => (bool) env('FACE_SEARCH_COMPRE_FACE_USE_BASE64', true),
        ],
        'aws_rekognition' => [
            'region' => env('FACE_SEARCH_AWS_REGION', env('AWS_REGION', env('AWS_DEFAULT_REGION', 'eu-central-1'))),
            'version' => env('FACE_SEARCH_AWS_REKOGNITION_VERSION', '2016-06-27'),
            'sts_version' => env('FACE_SEARCH_AWS_STS_VERSION', '2011-06-15'),
            'endpoint' => env('FACE_SEARCH_AWS_ENDPOINT', ''),
            'access_key_id' => env('FACE_SEARCH_AWS_ACCESS_KEY_ID', ''),
            'secret_access_key' => env('FACE_SEARCH_AWS_SECRET_ACCESS_KEY', ''),
            'session_token' => env('FACE_SEARCH_AWS_SESSION_TOKEN', ''),
            'retry_mode' => env('FACE_SEARCH_AWS_RETRY_MODE', 'standard'),
            'max_attempts_query' => (int) env('FACE_SEARCH_AWS_MAX_ATTEMPTS_QUERY', 3),
            'max_attempts_index' => (int) env('FACE_SEARCH_AWS_MAX_ATTEMPTS_INDEX', 5),
            'connect_timeout' => (float) env('FACE_SEARCH_AWS_CONNECT_TIMEOUT', 5),
            'connect_timeout_query' => (float) env('FACE_SEARCH_AWS_CONNECT_TIMEOUT_QUERY', env('FACE_SEARCH_AWS_CONNECT_TIMEOUT', 5)),
            'connect_timeout_index' => (float) env('FACE_SEARCH_AWS_CONNECT_TIMEOUT_INDEX', 6),
            'query_timeout' => (float) env('FACE_SEARCH_AWS_QUERY_TIMEOUT', 10),
            'index_timeout' => (float) env('FACE_SEARCH_AWS_INDEX_TIMEOUT', 20),
            'index_quality_filter' => env('FACE_SEARCH_AWS_INDEX_QUALITY_FILTER', 'AUTO'),
            'search_faces_quality_filter' => env('FACE_SEARCH_AWS_SEARCH_FACES_QUALITY_FILTER', 'NONE'),
            'search_users_quality_filter' => env('FACE_SEARCH_AWS_SEARCH_USERS_QUALITY_FILTER', 'NONE'),
            'search_face_match_threshold' => (float) env('FACE_SEARCH_AWS_SEARCH_FACE_MATCH_THRESHOLD', 80),
            'search_user_match_threshold' => (float) env('FACE_SEARCH_AWS_SEARCH_USER_MATCH_THRESHOLD', 80),
            'associate_user_match_threshold' => (float) env('FACE_SEARCH_AWS_ASSOCIATE_USER_MATCH_THRESHOLD', 75),
            'circuit_breaker' => [
                'failure_threshold' => (int) env('FACE_SEARCH_AWS_CIRCUIT_FAILURE_THRESHOLD', 3),
                'open_seconds' => (int) env('FACE_SEARCH_AWS_CIRCUIT_OPEN_SECONDS', 30),
            ],
            'user_vectors' => [
                'cluster_threshold' => (float) env('FACE_SEARCH_AWS_USER_VECTOR_CLUSTER_THRESHOLD', 0.35),
                'min_faces_per_user' => (int) env('FACE_SEARCH_AWS_USER_VECTOR_MIN_FACES', 5),
                'min_yaw_spread' => (float) env('FACE_SEARCH_AWS_USER_VECTOR_MIN_YAW_SPREAD', 8),
                'min_pitch_spread' => (float) env('FACE_SEARCH_AWS_USER_VECTOR_MIN_PITCH_SPREAD', 4),
            ],
            'detection_attributes' => array_values(array_filter(array_map(
                static fn (string $value): string => trim($value),
                explode(',', (string) env('FACE_SEARCH_AWS_DETECTION_ATTRIBUTES', 'DEFAULT,FACE_OCCLUDED')),
            ))),
        ],
    ],

    'preflight' => [
        'min_selfie_face_area_ratio' => (float) env('FACE_SEARCH_PREFLIGHT_MIN_SELFIE_FACE_AREA_RATIO', 0.08),
        'max_selfie_center_offset_ratio' => (float) env('FACE_SEARCH_PREFLIGHT_MAX_SELFIE_CENTER_OFFSET_RATIO', 0.22),
    ],
];
