<?php

namespace App\Modules\Hub\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class UpdateEventHubSettingsRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        $builder = app(\App\Modules\Hub\Support\HubBuilderPresetRegistry::class);
        $iconOptions = [
            'camera',
            'image',
            'monitor',
            'gamepad',
            'link',
            'calendar',
            'map-pin',
            'ticket',
            'music',
            'gift',
            'sparkles',
            'message-circle',
            'instagram',
        ];

        return [
            'is_enabled' => ['sometimes', 'boolean'],
            'headline' => ['nullable', 'string', 'max:180'],
            'subheadline' => ['nullable', 'string', 'max:255'],
            'welcome_text' => ['nullable', 'string', 'max:2000'],
            'hero_image_path' => ['nullable', 'string', 'max:255'],
            'button_style' => ['nullable', 'array'],
            'button_style.background_color' => ['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/'],
            'button_style.text_color' => ['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/'],
            'button_style.outline_color' => ['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/'],
            'builder_config' => ['nullable', 'array'],
            'builder_config.version' => ['nullable', 'integer', Rule::in([1])],
            'builder_config.layout_key' => ['nullable', Rule::in($builder::LAYOUT_KEYS)],
            'builder_config.theme_key' => ['nullable', Rule::in($builder::THEME_KEYS)],
            'builder_config.theme_tokens' => ['nullable', 'array'],
            'builder_config.theme_tokens.page_background' => ['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/'],
            'builder_config.theme_tokens.page_accent' => ['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/'],
            'builder_config.theme_tokens.surface_background' => ['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/'],
            'builder_config.theme_tokens.surface_border' => ['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/'],
            'builder_config.theme_tokens.text_primary' => ['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/'],
            'builder_config.theme_tokens.text_secondary' => ['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/'],
            'builder_config.theme_tokens.hero_overlay_color' => ['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/'],
            'builder_config.block_order' => ['nullable', 'array', 'max:8'],
            'builder_config.block_order.*' => ['required', Rule::in($builder::BLOCK_KEYS)],
            'builder_config.blocks' => ['nullable', 'array'],
            'builder_config.blocks.hero' => ['nullable', 'array'],
            'builder_config.blocks.hero.enabled' => ['nullable', 'boolean'],
            'builder_config.blocks.hero.show_logo' => ['nullable', 'boolean'],
            'builder_config.blocks.hero.show_badge' => ['nullable', 'boolean'],
            'builder_config.blocks.hero.show_meta_cards' => ['nullable', 'boolean'],
            'builder_config.blocks.hero.height' => ['nullable', Rule::in(['sm', 'md', 'lg'])],
            'builder_config.blocks.hero.overlay_opacity' => ['nullable', 'integer', 'min:0', 'max:90'],
            'builder_config.blocks.meta_cards' => ['nullable', 'array'],
            'builder_config.blocks.meta_cards.enabled' => ['nullable', 'boolean'],
            'builder_config.blocks.meta_cards.show_date' => ['nullable', 'boolean'],
            'builder_config.blocks.meta_cards.show_location' => ['nullable', 'boolean'],
            'builder_config.blocks.meta_cards.style' => ['nullable', Rule::in(['glass', 'solid', 'minimal'])],
            'builder_config.blocks.welcome' => ['nullable', 'array'],
            'builder_config.blocks.welcome.enabled' => ['nullable', 'boolean'],
            'builder_config.blocks.welcome.style' => ['nullable', Rule::in(['card', 'inline', 'bubble'])],
            'builder_config.blocks.countdown' => ['nullable', 'array'],
            'builder_config.blocks.countdown.enabled' => ['nullable', 'boolean'],
            'builder_config.blocks.countdown.style' => ['nullable', Rule::in(['cards', 'inline', 'minimal'])],
            'builder_config.blocks.countdown.target_mode' => ['nullable', Rule::in(['event_start', 'custom'])],
            'builder_config.blocks.countdown.target_at' => ['nullable', 'date'],
            'builder_config.blocks.countdown.title' => ['nullable', 'string', 'max:120'],
            'builder_config.blocks.countdown.completed_message' => ['nullable', 'string', 'max:180'],
            'builder_config.blocks.countdown.hide_after_start' => ['nullable', 'boolean'],
            'builder_config.blocks.info_grid' => ['nullable', 'array'],
            'builder_config.blocks.info_grid.enabled' => ['nullable', 'boolean'],
            'builder_config.blocks.info_grid.title' => ['nullable', 'string', 'max:120'],
            'builder_config.blocks.info_grid.style' => ['nullable', Rule::in(['cards', 'minimal', 'highlight'])],
            'builder_config.blocks.info_grid.columns' => ['nullable', 'integer', Rule::in([2, 3])],
            'builder_config.blocks.info_grid.items' => ['nullable', 'array', 'max:8'],
            'builder_config.blocks.info_grid.items.*.id' => ['required_with:builder_config.blocks.info_grid.items', 'string', 'max:80'],
            'builder_config.blocks.info_grid.items.*.title' => ['required_with:builder_config.blocks.info_grid.items', 'string', 'max:80'],
            'builder_config.blocks.info_grid.items.*.value' => ['required_with:builder_config.blocks.info_grid.items', 'string', 'max:140'],
            'builder_config.blocks.info_grid.items.*.description' => ['nullable', 'string', 'max:180'],
            'builder_config.blocks.info_grid.items.*.icon' => ['required_with:builder_config.blocks.info_grid.items', Rule::in($iconOptions)],
            'builder_config.blocks.info_grid.items.*.is_visible' => ['required_with:builder_config.blocks.info_grid.items', 'boolean'],
            'builder_config.blocks.cta_list' => ['nullable', 'array'],
            'builder_config.blocks.cta_list.enabled' => ['nullable', 'boolean'],
            'builder_config.blocks.cta_list.style' => ['nullable', Rule::in(['solid', 'outline', 'soft'])],
            'builder_config.blocks.cta_list.size' => ['nullable', Rule::in(['sm', 'md', 'lg'])],
            'builder_config.blocks.cta_list.icon_position' => ['nullable', Rule::in(['left', 'top'])],
            'builder_config.blocks.social_strip' => ['nullable', 'array'],
            'builder_config.blocks.social_strip.enabled' => ['nullable', 'boolean'],
            'builder_config.blocks.social_strip.style' => ['nullable', Rule::in(['icons', 'chips', 'cards'])],
            'builder_config.blocks.social_strip.size' => ['nullable', Rule::in(['sm', 'md', 'lg'])],
            'builder_config.blocks.social_strip.items' => ['nullable', 'array', 'max:12'],
            'builder_config.blocks.social_strip.items.*.id' => ['required_with:builder_config.blocks.social_strip.items', 'string', 'max:80'],
            'builder_config.blocks.social_strip.items.*.provider' => ['required_with:builder_config.blocks.social_strip.items', Rule::in(['instagram', 'whatsapp', 'tiktok', 'youtube', 'spotify', 'website', 'map', 'tickets'])],
            'builder_config.blocks.social_strip.items.*.label' => ['required_with:builder_config.blocks.social_strip.items', 'string', 'max:120'],
            'builder_config.blocks.social_strip.items.*.href' => ['nullable', 'string', 'max:2048', 'regex:/^(https?:\/\/|\/)/i'],
            'builder_config.blocks.social_strip.items.*.icon' => ['required_with:builder_config.blocks.social_strip.items', Rule::in($iconOptions)],
            'builder_config.blocks.social_strip.items.*.is_visible' => ['required_with:builder_config.blocks.social_strip.items', 'boolean'],
            'builder_config.blocks.social_strip.items.*.opens_in_new_tab' => ['required_with:builder_config.blocks.social_strip.items', 'boolean'],
            'builder_config.blocks.sponsor_strip' => ['nullable', 'array'],
            'builder_config.blocks.sponsor_strip.enabled' => ['nullable', 'boolean'],
            'builder_config.blocks.sponsor_strip.title' => ['nullable', 'string', 'max:120'],
            'builder_config.blocks.sponsor_strip.style' => ['nullable', Rule::in(['logos', 'cards', 'compact'])],
            'builder_config.blocks.sponsor_strip.items' => ['nullable', 'array', 'max:20'],
            'builder_config.blocks.sponsor_strip.items.*.id' => ['required_with:builder_config.blocks.sponsor_strip.items', 'string', 'max:80'],
            'builder_config.blocks.sponsor_strip.items.*.name' => ['required_with:builder_config.blocks.sponsor_strip.items', 'string', 'max:120'],
            'builder_config.blocks.sponsor_strip.items.*.subtitle' => ['nullable', 'string', 'max:160'],
            'builder_config.blocks.sponsor_strip.items.*.logo_path' => ['nullable', 'string', 'max:2048'],
            'builder_config.blocks.sponsor_strip.items.*.href' => ['nullable', 'string', 'max:2048', 'regex:/^(https?:\/\/|\/)/i'],
            'builder_config.blocks.sponsor_strip.items.*.is_visible' => ['required_with:builder_config.blocks.sponsor_strip.items', 'boolean'],
            'builder_config.blocks.sponsor_strip.items.*.opens_in_new_tab' => ['required_with:builder_config.blocks.sponsor_strip.items', 'boolean'],
            'buttons' => ['nullable', 'array', 'max:24'],
            'buttons.*.id' => ['required', 'string', 'max:80'],
            'buttons.*.type' => ['required', Rule::in(['preset', 'custom'])],
            'buttons.*.preset_key' => ['nullable', Rule::in(['upload', 'gallery', 'wall', 'play'])],
            'buttons.*.label' => ['required', 'string', 'max:180'],
            'buttons.*.icon' => ['required', Rule::in($iconOptions)],
            'buttons.*.href' => ['nullable', 'string', 'max:2048', 'regex:/^(https?:\/\/|\/)/i'],
            'buttons.*.is_visible' => ['required', 'boolean'],
            'buttons.*.opens_in_new_tab' => ['required', 'boolean'],
            'buttons.*.background_color' => ['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/'],
            'buttons.*.text_color' => ['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/'],
            'buttons.*.outline_color' => ['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/'],
        ];
    }
}
