<?php

namespace App\Modules\FaceSearch\Console;

use App\Modules\Events\Models\Event;
use App\Modules\FaceSearch\Actions\RollbackEventFaceSearchFallbackAction;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use JsonException;

class RollbackAwsFallbackRolloutCommand extends Command
{
    protected $signature = 'face-search:rollback-aws-fallback
        {--report= : Absolute path to a rollout report generated by face-search:promote-aws-fallback}';

    protected $description = 'Restore FaceSearch event settings from a rollback-ready rollout report.';

    public function handle(RollbackEventFaceSearchFallbackAction $action): int
    {
        $reportPath = (string) $this->option('report');

        if ($reportPath === '' || ! File::exists($reportPath)) {
            $this->error('Informe um report valido gerado pela promocao.');

            return self::FAILURE;
        }

        try {
            /** @var array<string, mixed> $report */
            $report = json_decode((string) File::get($reportPath), true, 512, JSON_THROW_ON_ERROR);
        } catch (JsonException) {
            $this->error('Nao foi possivel ler o report de rollout.');

            return self::FAILURE;
        }

        $events = collect((array) ($report['events'] ?? []))
            ->filter(fn (mixed $item): bool => is_array($item) && isset($item['event_id'], $item['previous_settings']))
            ->values();

        if ($events->isEmpty()) {
            $this->error('O report nao contem snapshots validos para rollback.');

            return self::FAILURE;
        }

        foreach ($events as $item) {
            $event = Event::query()->find((int) $item['event_id']);

            if (! $event) {
                $this->warn(sprintf('Evento %d nao encontrado, rollback ignorado.', (int) $item['event_id']));

                continue;
            }

            $result = $action->execute($event, (array) $item['previous_settings']);
            $this->line(sprintf('[%s] evento=%d %s', $result['status'], $event->id, $event->title));
        }

        $this->info('Rollback concluido.');

        return self::SUCCESS;
    }
}
